"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 1000
format = """
[](#d4f97e)\
$directory\
[](bg:#FCA17D fg:#d4f97e)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$nix_shell\
[ ](fg:#86BBD8 bg:#282c34)\
$line_break
"""
[directory]
style = "bg:#d4f97e fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[nix_shell]
symbol = ""
style = "bg:#86BBD8 fg:#FFFFFF"
format = '[ $symbol $shell ]($style)'

[line_break]
disabled = true
